# Generated by Django 5.1.7 on 2025-04-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.IntegerField()),
                ('category', models.IntegerField()),
                ('amt', models.FloatField()),
                ('gender', models.IntegerField()),
                ('age', models.FloatField()),
                ('job', models.IntegerField()),
                ('distance_km', models.FloatField()),
                ('unix_time', models.IntegerField()),
                ('trans_hour', models.IntegerField()),
                ('is_fraud', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='transaction_categor_d2bef2_idx'), models.Index(fields=['is_fraud'], name='transaction_is_frau_237d47_idx'), models.Index(fields=['merchant'], name='transaction_merchan_cff36b_idx')],
            },
        ),
    ]
